### ISSUE TITLE
홈뷰 급식 파트 데이터 연동

### ISSUE THREAD

**Issue by hprize** [hprize/GI_App_Project#12]
## Issue
홈뷰 급식파트 데이터 연동
요일별로 자동으로 바뀌는 급식데이터 구현
오전일땐 점심 파트 제목 강조, 오후일땐 저녁 파트 제목 강조
## todo
- [ ] 파이어베이스 급식 데이터 컬렉션 생성
- [ ] 컬렉션 문서 내용 화면에 띄우기
- [ ] 날짜 데이터 불러오기, 불러온 데이터에 따라서 자동으로 요일별 급식 변경 기능
- [ ] 시간 데이터 불러오기, 오전일땐 점심 파트 제목 강조, 오후일땐 저녁 파트 제목 강조
