### ISSUE TITLE
급식 뷰 UI 구성 / 데이터 연동

### ISSUE THREAD

**Issue by hprize** [hprize/GI_App_Project#14]
## Issue
급식 뷰 UI 구성 - 상단 정보 / Best 메뉴 / 일주일 급식 메뉴
급식 데이터 연동 
## todo
- [ ] 순서대로 UI 짜기
- [ ] 급식 데이터 연동
- [ ] 카드 뒤집기 인터렉션 구현
