### ISSUE TITLE
홈 화면 UI / 탭바 UI

### ISSUE THREAD

**Issue by hprize** [hprize/GI_App_Project#8]
## Issue
홈 화면 UI (공지사항, 급식, 시간표) 수정 / 탭바 UI 구성

## todo
- [x] 홈 화면 UI 세부사항 수정
- [x] 탭바 UI 짜기
- [x] 탭바 애니메이션 추가
